services:
  - type: web
    name: video-chat
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://video-chat-7dw0.onrender.com
      - key: NEXT_PUBLIC_WHEREBY_SUBDOMAIN
        value: sanhome
      - key: WHEREBY_API_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmFwcGVhci5pbiIsImF1ZCI6Imh0dHBzOi8vYXBpLmFwcGVhci5pbi92MSIsImV4cCI6OTAwNzE5OTI1NDc0MDk5MSwiaWF0IjoxNzUyNzYyMDczLCJvcmdhbml6YXRpb25JZCI6MzE2MTI5LCJqdGkiOiIwNGRjYTZlNy1hZWE4LTRkYjctOTk5My03YWVkNmNhOTE3ODgifQ.exhr2MtrRbLjV21Ffal4r6kc5iioRyh3i-I89iCekkk 